# version: 도커 컴포즈의 버전
version: "3"
# services: 실행하려는 여러 컨테이너들
    # redis-server: 컨테이너 이름
        # image: 컨테이너에서 사용하는 이미지
    # node-app: 컨테이너 이름
        # build: docker-compose up이하의 옵션들을 줄이기 위한 설정
            # context: 도커이미지를 구성하기 위한 파일과 폴더들이 있는 위치
            # dockerfile: 도커 파일의 이름을 지정. docker run -f 파일명과 동일
            # volumes:
                # - 참조하지 않을 경로
                # - 참조할 경로
            # build: dockerfile 디렉터리
        # ports: 포트 매핑. 로컬:컨테이너 포트
        
        
        # stdin_open: true(react app의 종료시 버그가 있어 추가)

services:
    redis-server:
        image: "redis"
    node-app:
        build: .
        ports:
            - "5000:8080"
